# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76be4b821fa363b06456e0fefe54beac694658dd7eb3330264fb3fe5756ffeb32145d3a504163954146b10838820525dc75bbde88730b751765ee284d630dd7

test:
  secret_key_base: faa87b3cff58cb32472b4026de85d0fc2cf49bdb6cc993f1feb7526897ff1971513bfe2951bf632b07621de7ece57cdcd1822078fdd96bbea92cdc05bf01db4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
